"""
Django settings for ECommerce project.
Generated by 'django-admin startproject' using Django 5.2.1.
"""

from pathlib import Path
import os

# === Base Directory ===
BASE_DIR = Path(__file__).resolve().parent.parent

# === Security ===
SECRET_KEY = 'django-insecure-17u1mhs&%xadi*v3ml8x&u7(4jh0ql2zbp_fp#(!@!3bwhy%t6'
DEBUG = True
ALLOWED_HOSTS = []

# === Installed Apps ===
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.ecommerce_admin',  # your custom admin app
    'apps.ecommerce_user',   # optional user app
]

# === Middleware ===
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

# === Root URLs & Templates ===
ROOT_URLCONF = 'ECommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'apps', 'ecommerce_admin', 'templates'),
            os.path.join(BASE_DIR, 'apps', 'ecommerce_user', 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ECommerce.wsgi.application'

# === Database (MySQL) ===
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "ECommerce",
        "USER": "root",
        "PASSWORD": "uppi_008",
        "HOST": "127.0.0.1",
        "PORT": "3306",
    }
}

# === Custom User Model ===
AUTH_USER_MODEL = 'ecommerce_admin.Admin'

# === Authentication Backends ===
AUTHENTICATION_BACKENDS = [
    'apps.ecommerce_admin.authentication.CRNEmailMobileAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# === Password Validators ===
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# === Localization ===
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# === Static Files ===
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# === Default Primary Key Field ===
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# === Email Configuration ===
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'upendrarajulapati8@gmail.com'  
EMAIL_HOST_PASSWORD = 'euld wjtk ipvt ysvt'
